"""Inference interfaces for replay, compatibility checks, and MLE fitting."""

from .bayes import (
    BayesFitResult,
    IndependentPriorProgram,
    PosteriorCandidate,
    PriorProgram,
    beta_log_prior,
    build_map_fit_function,
    log_normal_log_prior,
    normal_log_prior,
    uniform_log_prior,
)
from .bayes_config import (
    hierarchical_map_spec_from_config,
    map_fit_spec_from_config,
    prior_program_from_config,
)
from .block_strategy import BlockFitStrategy
from .cli import run_fit_cli
from .compatibility import CompatibilityReport, assert_trace_compatible, check_trace_compatibility
from .config import (
    ModelComponentSpec,
    fit_block_from_config,
    fit_dataset_from_config,
    fit_spec_from_config,
    fit_study_from_config,
    fit_subject_from_config,
    model_component_spec_from_config,
)
from .config_dispatch import (
    HIERARCHICAL_ESTIMATORS,
    HIERARCHICAL_MCMC_ESTIMATORS,
    MAP_ESTIMATORS,
    MCMC_ESTIMATORS,
    MLE_ESTIMATORS,
    fit_block_auto_from_config,
    fit_dataset_auto_from_config,
    fit_study_auto_from_config,
    fit_subject_auto_from_config,
)
from .fit_result import BestFitSummary, extract_best_fit_summary
from .fitting import (
    FitInferenceType,
    FitSpec,
    MLESolverType,
    build_model_fit_function,
    coerce_episode_trace,
    fit_model,
    fit_model_from_registry,
)
from .hierarchical import (
    HierarchicalBlockResult,
    HierarchicalStudyMapResult,
    HierarchicalSubjectMapResult,
)
from .hierarchical_mcmc import (
    HierarchicalMCMCDraw,
    HierarchicalPosteriorCandidate,
    HierarchicalStudyPosteriorResult,
    HierarchicalSubjectPosteriorResult,
)
from .hierarchical_stan import (
    sample_study_hierarchical_posterior_stan,
    sample_subject_hierarchical_posterior_stan,
)
from .likelihood import ActionReplayLikelihood, ActorSubsetReplayLikelihood, LikelihoodProgram
from .likelihood_config import likelihood_program_from_config
from .mcmc import MCMCDiagnostics
from .mcmc_config import (
    HierarchicalStanEstimatorSpec,
    hierarchical_stan_estimator_spec_from_config,
    sample_study_hierarchical_posterior_from_config,
    sample_subject_hierarchical_posterior_from_config,
)
from .mle import (
    GridSearchMLEEstimator,
    MLECandidate,
    MLEFitResult,
    ScipyMinimizeDiagnostics,
    ScipyMinimizeMLEEstimator,
    TransformedScipyMinimizeMLEEstimator,
)
from .model_selection import (
    CandidateComparison,
    CandidateFitSpec,
    ModelComparisonResult,
    RegistryCandidateFitSpec,
    SelectionCriterion,
    compare_candidate_models,
    compare_registry_candidate_models,
)
from .model_selection_cli import run_model_comparison_cli
from .model_selection_config import (
    build_fit_function_from_model_config,
    compare_dataset_candidates_from_config,
    compare_study_candidates_from_config,
    compare_subject_candidates_from_config,
)
from .model_selection_tabular import (
    compare_study_csv_candidates_from_config,
    compare_trial_csv_candidates_from_config,
)
from .posterior import (
    PosteriorParameterSummary,
    PosteriorSamples,
    PosteriorSummary,
    posterior_summary_records,
    summarize_posterior,
)
from .serialization import (
    block_fit_records,
    hierarchical_mcmc_study_draw_records,
    hierarchical_mcmc_study_summary_records,
    hierarchical_mcmc_subject_draw_records,
    hierarchical_mcmc_subject_summary_records,
    hierarchical_study_block_records,
    hierarchical_study_summary_records,
    hierarchical_subject_block_records,
    hierarchical_subject_summary_records,
    map_block_fit_records,
    map_study_fit_records,
    map_study_summary_records,
    map_subject_fit_records,
    map_subject_summary_records,
    model_comparison_records,
    study_fit_records,
    study_model_comparison_records,
    study_model_comparison_subject_records,
    study_summary_records,
    subject_fit_records,
    subject_model_comparison_records,
    subject_summary_records,
    write_hierarchical_mcmc_study_draw_records_csv,
    write_hierarchical_mcmc_study_summary_csv,
    write_hierarchical_study_block_records_csv,
    write_hierarchical_study_summary_csv,
    write_map_study_fit_records_csv,
    write_map_study_fit_summary_csv,
    write_model_comparison_csv,
    write_posterior_summary_csv,
    write_records_csv,
    write_study_fit_records_csv,
    write_study_fit_summary_csv,
    write_study_model_comparison_csv,
    write_study_model_comparison_subject_csv,
    write_subject_model_comparison_csv,
)
from .study_fitting import (
    BlockFitResult,
    StudyFitResult,
    SubjectFitResult,
    fit_block_data,
    fit_study_data,
    fit_subject_data,
)
from .study_model_selection import (
    StudyCandidateComparison,
    StudyModelComparisonResult,
    SubjectCandidateComparison,
    SubjectModelComparisonResult,
    compare_study_candidate_models,
    compare_subject_candidate_models,
)
from .tabular import fit_study_csv_from_config, fit_trial_csv_from_config
from .transforms import (
    ParameterTransform,
    identity_transform,
    positive_log_transform,
    unit_interval_logit_transform,
)

__all__ = [
    "ActionReplayLikelihood",
    "ActorSubsetReplayLikelihood",
    "BayesFitResult",
    "BlockFitResult",
    "BlockFitStrategy",
    "CandidateComparison",
    "CandidateFitSpec",
    "CompatibilityReport",
    "FitInferenceType",
    "FitSpec",
    "GridSearchMLEEstimator",
    "HIERARCHICAL_MCMC_ESTIMATORS",
    "HIERARCHICAL_ESTIMATORS",
    "HierarchicalStanEstimatorSpec",
    "HierarchicalBlockResult",
    "HierarchicalMCMCDraw",
    "HierarchicalPosteriorCandidate",
    "HierarchicalStudyMapResult",
    "HierarchicalStudyPosteriorResult",
    "HierarchicalSubjectMapResult",
    "HierarchicalSubjectPosteriorResult",
    "IndependentPriorProgram",
    "LikelihoodProgram",
    "MAP_ESTIMATORS",
    "MCMC_ESTIMATORS",
    "MLE_ESTIMATORS",
    "MCMCDiagnostics",
    "BestFitSummary",
    "MLECandidate",
    "MLEFitResult",
    "MLESolverType",
    "ModelComparisonResult",
    "ModelComponentSpec",
    "PosteriorCandidate",
    "PriorProgram",
    "ParameterTransform",
    "PosteriorParameterSummary",
    "PosteriorSamples",
    "PosteriorSummary",
    "RegistryCandidateFitSpec",
    "ScipyMinimizeDiagnostics",
    "ScipyMinimizeMLEEstimator",
    "SelectionCriterion",
    "StudyFitResult",
    "StudyCandidateComparison",
    "StudyModelComparisonResult",
    "SubjectFitResult",
    "SubjectCandidateComparison",
    "SubjectModelComparisonResult",
    "TransformedScipyMinimizeMLEEstimator",
    "assert_trace_compatible",
    "beta_log_prior",
    "block_fit_records",
    "hierarchical_study_block_records",
    "hierarchical_study_summary_records",
    "hierarchical_mcmc_study_draw_records",
    "hierarchical_mcmc_study_summary_records",
    "hierarchical_mcmc_subject_draw_records",
    "hierarchical_mcmc_subject_summary_records",
    "hierarchical_subject_block_records",
    "hierarchical_subject_summary_records",
    "map_block_fit_records",
    "map_study_fit_records",
    "map_study_summary_records",
    "map_subject_fit_records",
    "map_subject_summary_records",
    "model_comparison_records",
    "study_model_comparison_records",
    "study_model_comparison_subject_records",
    "build_model_fit_function",
    "build_map_fit_function",
    "check_trace_compatibility",
    "coerce_episode_trace",
    "build_fit_function_from_model_config",
    "compare_dataset_candidates_from_config",
    "extract_best_fit_summary",
    "compare_candidate_models",
    "compare_study_candidate_models",
    "compare_study_candidates_from_config",
    "compare_study_csv_candidates_from_config",
    "compare_subject_candidate_models",
    "compare_subject_candidates_from_config",
    "compare_trial_csv_candidates_from_config",
    "compare_registry_candidate_models",
    "fit_block_data",
    "fit_block_auto_from_config",
    "fit_block_from_config",
    "fit_dataset_from_config",
    "fit_dataset_auto_from_config",
    "fit_model",
    "fit_model_from_registry",
    "fit_spec_from_config",
    "sample_study_hierarchical_posterior_from_config",
    "fit_study_data",
    "fit_study_auto_from_config",
    "sample_study_hierarchical_posterior_stan",
    "fit_study_from_config",
    "sample_subject_hierarchical_posterior_stan",
    "sample_subject_hierarchical_posterior_from_config",
    "fit_subject_auto_from_config",
    "fit_subject_data",
    "fit_subject_from_config",
    "fit_study_csv_from_config",
    "fit_trial_csv_from_config",
    "identity_transform",
    "hierarchical_stan_estimator_spec_from_config",
    "hierarchical_map_spec_from_config",
    "log_normal_log_prior",
    "likelihood_program_from_config",
    "map_fit_spec_from_config",
    "model_component_spec_from_config",
    "normal_log_prior",
    "positive_log_transform",
    "posterior_summary_records",
    "study_fit_records",
    "study_summary_records",
    "subject_fit_records",
    "subject_model_comparison_records",
    "subject_summary_records",
    "summarize_posterior",
    "prior_program_from_config",
    "run_fit_cli",
    "run_model_comparison_cli",
    "uniform_log_prior",
    "unit_interval_logit_transform",
    "write_hierarchical_study_block_records_csv",
    "write_hierarchical_mcmc_study_draw_records_csv",
    "write_hierarchical_mcmc_study_summary_csv",
    "write_hierarchical_study_summary_csv",
    "write_map_study_fit_records_csv",
    "write_map_study_fit_summary_csv",
    "write_model_comparison_csv",
    "write_posterior_summary_csv",
    "write_study_model_comparison_csv",
    "write_study_model_comparison_subject_csv",
    "write_subject_model_comparison_csv",
    "write_records_csv",
    "write_study_fit_records_csv",
    "write_study_fit_summary_csv",
]
