"""Inference interfaces for replay, compatibility checks, and MLE fitting."""

from .compatibility import CompatibilityReport, assert_trace_compatible, check_trace_compatibility
from .config import (
    ModelComponentSpec,
    fit_block_from_config,
    fit_dataset_from_config,
    fit_spec_from_config,
    fit_study_from_config,
    fit_subject_from_config,
    model_component_spec_from_config,
)
from .fitting import (
    EstimatorType,
    FitSpec,
    build_model_fit_function,
    coerce_episode_trace,
    fit_model,
    fit_model_from_registry,
)
from .likelihood import ActionReplayLikelihood, LikelihoodProgram
from .mle import (
    GridSearchMLEEstimator,
    MLECandidate,
    MLEFitResult,
    ScipyMinimizeDiagnostics,
    ScipyMinimizeMLEEstimator,
    TransformedScipyMinimizeMLEEstimator,
)
from .model_selection import (
    CandidateComparison,
    CandidateFitSpec,
    ModelComparisonResult,
    RegistryCandidateFitSpec,
    SelectionCriterion,
    compare_candidate_models,
    compare_registry_candidate_models,
)
from .serialization import (
    block_fit_records,
    study_fit_records,
    study_summary_records,
    subject_fit_records,
    subject_summary_records,
    write_records_csv,
    write_study_fit_records_csv,
    write_study_fit_summary_csv,
)
from .study_fitting import (
    BlockFitResult,
    StudyFitResult,
    SubjectFitResult,
    fit_block_data,
    fit_study_data,
    fit_subject_data,
)
from .transforms import ParameterTransform, identity_transform, positive_log_transform, unit_interval_logit_transform

__all__ = [
    "ActionReplayLikelihood",
    "BlockFitResult",
    "CandidateComparison",
    "CandidateFitSpec",
    "CompatibilityReport",
    "EstimatorType",
    "FitSpec",
    "GridSearchMLEEstimator",
    "LikelihoodProgram",
    "MLECandidate",
    "MLEFitResult",
    "ModelComparisonResult",
    "ModelComponentSpec",
    "ParameterTransform",
    "RegistryCandidateFitSpec",
    "ScipyMinimizeDiagnostics",
    "ScipyMinimizeMLEEstimator",
    "SelectionCriterion",
    "StudyFitResult",
    "SubjectFitResult",
    "TransformedScipyMinimizeMLEEstimator",
    "assert_trace_compatible",
    "block_fit_records",
    "build_model_fit_function",
    "check_trace_compatibility",
    "coerce_episode_trace",
    "compare_candidate_models",
    "compare_registry_candidate_models",
    "fit_block_data",
    "fit_block_from_config",
    "fit_dataset_from_config",
    "fit_model",
    "fit_model_from_registry",
    "fit_spec_from_config",
    "fit_study_data",
    "fit_study_from_config",
    "fit_subject_data",
    "fit_subject_from_config",
    "identity_transform",
    "model_component_spec_from_config",
    "positive_log_transform",
    "study_fit_records",
    "study_summary_records",
    "subject_fit_records",
    "subject_summary_records",
    "unit_interval_logit_transform",
    "write_records_csv",
    "write_study_fit_records_csv",
    "write_study_fit_summary_csv",
]
