"""Inference interfaces for replay, compatibility checks, and Stan/MLE fitting."""

from .block_strategy import BlockFitStrategy
from .cli import run_fit_cli
from .compatibility import CompatibilityReport, assert_trace_compatible, check_trace_compatibility
from .config import (
    ModelComponentSpec,
    fit_block_from_config,
    fit_dataset_from_config,
    fit_spec_from_config,
    fit_study_from_config,
    fit_subject_from_config,
    model_component_spec_from_config,
)
from .config_dispatch import (
    BAYES_ESTIMATORS,
    MAP_ESTIMATORS,
    MCMC_ESTIMATORS,
    MLE_ESTIMATORS,
    STUDY_BAYES_ESTIMATORS,
    SUBJECT_BAYES_ESTIMATORS,
    fit_block_auto_from_config,
    fit_dataset_auto_from_config,
    fit_study_auto_from_config,
    fit_subject_auto_from_config,
)
from .fit_result import BestFitSummary, extract_best_fit_summary
from .fitting import (
    FitInferenceType,
    FitSpec,
    MLESolverType,
    coerce_episode_trace,
    fit_dataset,
    fit_dataset_from_registry,
)
from .hierarchical_posterior import (
    StanPosteriorDraw,
    StudySubjectBlockHierarchyPosteriorCandidate,
    StudySubjectBlockHierarchyPosteriorResult,
    StudySubjectHierarchyPosteriorCandidate,
    StudySubjectHierarchyPosteriorResult,
    SubjectBlockHierarchyPosteriorCandidate,
    SubjectBlockHierarchyPosteriorResult,
    SubjectSharedPosteriorCandidate,
    SubjectSharedPosteriorResult,
)
from .hierarchical_stan import (
    draw_study_subject_block_hierarchy_posterior_stan,
    draw_study_subject_hierarchy_posterior_stan,
    draw_subject_block_hierarchy_posterior_stan,
    draw_subject_shared_posterior_stan,
    estimate_study_subject_block_hierarchy_map_stan,
    estimate_study_subject_hierarchy_map_stan,
    estimate_subject_block_hierarchy_map_stan,
    estimate_subject_shared_map_stan,
)
from .likelihood import ActionReplayLikelihood, ActorSubsetReplayLikelihood, LikelihoodProgram
from .likelihood_config import likelihood_program_from_config
from .stan_config import (
    STAN_ESTIMATORS,
    STUDY_MAP_ESTIMATORS,
    STUDY_NUTS_ESTIMATORS,
    STUDY_STAN_ESTIMATORS,
    SUBJECT_MAP_ESTIMATORS,
    SUBJECT_NUTS_ESTIMATORS,
    SUBJECT_STAN_ESTIMATORS,
    StanEstimatorSpec,
    infer_study_stan_from_config,
    infer_subject_stan_from_config,
    stan_estimator_spec_from_config,
)
from .mcmc_diagnostics import MCMCDiagnostics
from .mle import (
    GridSearchMLEEstimator,
    MLECandidate,
    MLEFitResult,
    ScipyMinimizeDiagnostics,
    ScipyMinimizeMLEEstimator,
    TransformedScipyMinimizeMLEEstimator,
)
from .model_selection import (
    CandidateComparison,
    CandidateFitSpec,
    ModelComparisonResult,
    RegistryCandidateFitSpec,
    SelectionCriterion,
    compare_candidate_models,
    compare_registry_candidate_models,
)
from .model_selection_cli import run_model_comparison_cli
from .model_selection_config import (
    build_fit_function_from_model_config,
    compare_dataset_candidates_from_config,
    compare_study_candidates_from_config,
    compare_subject_candidates_from_config,
)
from .model_selection_tabular import (
    compare_study_csv_candidates_from_config,
    compare_trial_csv_candidates_from_config,
)
from .posterior import (
    PosteriorParameterSummary,
    PosteriorSamples,
    PosteriorSummary,
    posterior_summary_records,
    summarize_posterior,
)
from .serialization import (
    block_fit_records,
    hierarchical_mcmc_study_draw_records,
    hierarchical_mcmc_study_summary_records,
    hierarchical_mcmc_subject_draw_records,
    hierarchical_mcmc_subject_summary_records,
    model_comparison_records,
    study_fit_records,
    study_model_comparison_records,
    study_model_comparison_subject_records,
    study_summary_records,
    subject_fit_records,
    subject_model_comparison_records,
    subject_summary_records,
    write_hierarchical_mcmc_study_draw_records_csv,
    write_hierarchical_mcmc_study_summary_csv,
    write_model_comparison_csv,
    write_posterior_summary_csv,
    write_records_csv,
    write_study_fit_records_csv,
    write_study_fit_summary_csv,
    write_study_model_comparison_csv,
    write_study_model_comparison_subject_csv,
    write_subject_model_comparison_csv,
)
from .study_fitting import (
    BlockFitResult,
    StudyFitResult,
    SubjectFitResult,
    fit_block_data,
    fit_study_data,
    fit_subject_data,
)
from .study_model_selection import (
    StudyCandidateComparison,
    StudyModelComparisonResult,
    SubjectCandidateComparison,
    SubjectModelComparisonResult,
    compare_study_candidate_models,
    compare_subject_candidate_models,
)
from .tabular import fit_study_csv_from_config, fit_trial_csv_from_config
from .transforms import (
    ParameterTransform,
    identity_transform,
    positive_log_transform,
    unit_interval_logit_transform,
)

__all__ = [
    "ActionReplayLikelihood",
    "ActorSubsetReplayLikelihood",
    "BlockFitResult",
    "BlockFitStrategy",
    "CandidateComparison",
    "CandidateFitSpec",
    "CompatibilityReport",
    "FitInferenceType",
    "FitSpec",
    "GridSearchMLEEstimator",
    "BAYES_ESTIMATORS",
    "STUDY_BAYES_ESTIMATORS",
    "SUBJECT_BAYES_ESTIMATORS",
    "STAN_ESTIMATORS",
    "STUDY_MAP_ESTIMATORS",
    "STUDY_NUTS_ESTIMATORS",
    "STUDY_STAN_ESTIMATORS",
    "SUBJECT_MAP_ESTIMATORS",
    "SUBJECT_NUTS_ESTIMATORS",
    "SUBJECT_STAN_ESTIMATORS",
    "StanEstimatorSpec",
    "StanPosteriorDraw",
    "StudySubjectBlockHierarchyPosteriorCandidate",
    "StudySubjectBlockHierarchyPosteriorResult",
    "StudySubjectHierarchyPosteriorCandidate",
    "StudySubjectHierarchyPosteriorResult",
    "SubjectBlockHierarchyPosteriorCandidate",
    "SubjectBlockHierarchyPosteriorResult",
    "SubjectSharedPosteriorCandidate",
    "SubjectSharedPosteriorResult",
    "LikelihoodProgram",
    "MAP_ESTIMATORS",
    "MCMC_ESTIMATORS",
    "MLE_ESTIMATORS",
    "MCMCDiagnostics",
    "BestFitSummary",
    "MLECandidate",
    "MLEFitResult",
    "MLESolverType",
    "ModelComparisonResult",
    "ModelComponentSpec",
    "ParameterTransform",
    "PosteriorParameterSummary",
    "PosteriorSamples",
    "PosteriorSummary",
    "RegistryCandidateFitSpec",
    "ScipyMinimizeDiagnostics",
    "ScipyMinimizeMLEEstimator",
    "SelectionCriterion",
    "StudyFitResult",
    "StudyCandidateComparison",
    "StudyModelComparisonResult",
    "SubjectFitResult",
    "SubjectCandidateComparison",
    "SubjectModelComparisonResult",
    "TransformedScipyMinimizeMLEEstimator",
    "assert_trace_compatible",
    "block_fit_records",
    "hierarchical_mcmc_study_draw_records",
    "hierarchical_mcmc_study_summary_records",
    "hierarchical_mcmc_subject_draw_records",
    "hierarchical_mcmc_subject_summary_records",
    "model_comparison_records",
    "study_model_comparison_records",
    "study_model_comparison_subject_records",
    "check_trace_compatibility",
    "coerce_episode_trace",
    "build_fit_function_from_model_config",
    "compare_dataset_candidates_from_config",
    "extract_best_fit_summary",
    "compare_candidate_models",
    "compare_study_candidate_models",
    "compare_study_candidates_from_config",
    "compare_study_csv_candidates_from_config",
    "compare_subject_candidate_models",
    "compare_subject_candidates_from_config",
    "compare_trial_csv_candidates_from_config",
    "compare_registry_candidate_models",
    "fit_block_data",
    "fit_block_auto_from_config",
    "fit_block_from_config",
    "fit_dataset_from_config",
    "fit_dataset_auto_from_config",
    "fit_dataset",
    "fit_dataset_from_registry",
    "fit_spec_from_config",
    "infer_study_stan_from_config",
    "fit_study_data",
    "fit_study_auto_from_config",
    "estimate_study_subject_block_hierarchy_map_stan",
    "estimate_study_subject_hierarchy_map_stan",
    "draw_study_subject_block_hierarchy_posterior_stan",
    "draw_study_subject_hierarchy_posterior_stan",
    "fit_study_from_config",
    "estimate_subject_block_hierarchy_map_stan",
    "estimate_subject_shared_map_stan",
    "draw_subject_block_hierarchy_posterior_stan",
    "draw_subject_shared_posterior_stan",
    "infer_subject_stan_from_config",
    "fit_subject_auto_from_config",
    "fit_subject_data",
    "fit_subject_from_config",
    "fit_study_csv_from_config",
    "fit_trial_csv_from_config",
    "identity_transform",
    "stan_estimator_spec_from_config",
    "likelihood_program_from_config",
    "model_component_spec_from_config",
    "positive_log_transform",
    "posterior_summary_records",
    "study_fit_records",
    "study_summary_records",
    "subject_fit_records",
    "subject_model_comparison_records",
    "subject_summary_records",
    "summarize_posterior",
    "run_fit_cli",
    "run_model_comparison_cli",
    "unit_interval_logit_transform",
    "write_hierarchical_mcmc_study_draw_records_csv",
    "write_hierarchical_mcmc_study_summary_csv",
    "write_model_comparison_csv",
    "write_posterior_summary_csv",
    "write_study_model_comparison_csv",
    "write_study_model_comparison_subject_csv",
    "write_subject_model_comparison_csv",
    "write_records_csv",
    "write_study_fit_records_csv",
    "write_study_fit_summary_csv",
]
