"""Top-level package for ``comp_model``.

The package is organized around a generic decision loop:

1. a :class:`~comp_model.core.contracts.DecisionProblem` generates observations,
2. an :class:`~comp_model.core.contracts.AgentModel` chooses actions,
3. the problem returns outcomes,
4. the agent updates internal memory.

For multi-phase tasks, use
:func:`~comp_model.runtime.engine.run_trial_program` with a
:class:`~comp_model.runtime.program.TrialProgram`.

Notes
-----
Bandit is intentionally implemented as a specific problem under
``comp_model.problems`` and is not used as the central abstraction.
"""

from .core.contracts import AgentModel, DecisionContext, DecisionProblem
from .core.data import StudyData
from .inference import (
    ActorSubsetReplayLikelihood,
    FitSpec,
    IndependentPriorProgram,
    MapFitSpec,
    ScipyMapBayesEstimator,
    TransformedScipyMapBayesEstimator,
    compare_candidate_models,
    compare_dataset_candidates_from_config,
    compare_registry_candidate_models,
    compare_study_candidate_models,
    compare_study_candidates_from_config,
    compare_study_csv_candidates_from_config,
    compare_subject_candidate_models,
    compare_subject_candidates_from_config,
    compare_trial_csv_candidates_from_config,
    fit_block_auto_from_config,
    fit_dataset_auto_from_config,
    fit_dataset_from_config,
    fit_map_block_data,
    fit_map_block_from_config,
    fit_map_dataset_from_config,
    fit_map_model,
    fit_map_model_from_registry,
    fit_map_study_data,
    fit_map_study_from_config,
    fit_map_subject_data,
    fit_map_subject_from_config,
    fit_model,
    fit_model_from_registry,
    fit_study_auto_from_config,
    fit_study_csv_from_config,
    fit_study_data,
    fit_study_from_config,
    fit_study_hierarchical_map,
    fit_study_hierarchical_map_from_config,
    fit_subject_auto_from_config,
    fit_subject_hierarchical_map,
    fit_subject_hierarchical_map_from_config,
    fit_trial_csv_from_config,
    likelihood_program_from_config,
    normal_log_prior,
    posterior_summary_records,
    run_fit_cli,
    run_model_comparison_cli,
    sample_study_hierarchical_posterior_from_config,
    sample_study_hierarchical_posterior_stan,
    sample_subject_hierarchical_posterior_from_config,
    sample_subject_hierarchical_posterior_stan,
    summarize_posterior,
    uniform_log_prior,
    write_hierarchical_mcmc_study_draw_records_csv,
    write_hierarchical_mcmc_study_summary_csv,
    write_hierarchical_study_block_records_csv,
    write_hierarchical_study_summary_csv,
    write_map_study_fit_records_csv,
    write_map_study_fit_summary_csv,
    write_model_comparison_csv,
    write_posterior_summary_csv,
    write_study_fit_records_csv,
    write_study_fit_summary_csv,
    write_study_model_comparison_csv,
    write_study_model_comparison_subject_csv,
    write_subject_model_comparison_csv,
)
from .io import (
    read_study_decisions_csv,
    read_trial_decisions_csv,
    study_decision_rows,
    write_study_decisions_csv,
    write_trial_decisions_csv,
)
from .recovery import (
    load_json_config,
    run_model_recovery,
    run_model_recovery_from_config,
    run_parameter_recovery,
    run_parameter_recovery_from_config,
    run_recovery_cli,
)
from .runtime.engine import SimulationConfig, run_episode, run_trial_program

__all__ = [
    "AgentModel",
    "DecisionContext",
    "DecisionProblem",
    "FitSpec",
    "ActorSubsetReplayLikelihood",
    "IndependentPriorProgram",
    "MapFitSpec",
    "ScipyMapBayesEstimator",
    "SimulationConfig",
    "StudyData",
    "TransformedScipyMapBayesEstimator",
    "compare_candidate_models",
    "compare_dataset_candidates_from_config",
    "compare_registry_candidate_models",
    "compare_study_candidate_models",
    "compare_study_candidates_from_config",
    "compare_study_csv_candidates_from_config",
    "compare_subject_candidate_models",
    "compare_subject_candidates_from_config",
    "compare_trial_csv_candidates_from_config",
    "fit_block_auto_from_config",
    "fit_dataset_from_config",
    "fit_dataset_auto_from_config",
    "fit_map_block_data",
    "fit_map_block_from_config",
    "fit_map_dataset_from_config",
    "fit_map_study_data",
    "fit_map_study_from_config",
    "fit_map_subject_data",
    "fit_map_subject_from_config",
    "fit_map_model",
    "fit_map_model_from_registry",
    "fit_model",
    "fit_model_from_registry",
    "sample_study_hierarchical_posterior_from_config",
    "fit_study_data",
    "fit_study_auto_from_config",
    "fit_study_hierarchical_map",
    "fit_study_hierarchical_map_from_config",
    "fit_study_csv_from_config",
    "sample_study_hierarchical_posterior_stan",
    "fit_study_from_config",
    "fit_subject_hierarchical_map",
    "fit_subject_hierarchical_map_from_config",
    "fit_trial_csv_from_config",
    "sample_subject_hierarchical_posterior_stan",
    "sample_subject_hierarchical_posterior_from_config",
    "fit_subject_auto_from_config",
    "run_fit_cli",
    "run_model_comparison_cli",
    "load_json_config",
    "likelihood_program_from_config",
    "normal_log_prior",
    "write_hierarchical_mcmc_study_draw_records_csv",
    "write_hierarchical_mcmc_study_summary_csv",
    "posterior_summary_records",
    "run_model_recovery",
    "run_model_recovery_from_config",
    "run_parameter_recovery",
    "run_parameter_recovery_from_config",
    "run_recovery_cli",
    "run_episode",
    "run_trial_program",
    "read_study_decisions_csv",
    "read_trial_decisions_csv",
    "study_decision_rows",
    "write_study_decisions_csv",
    "write_trial_decisions_csv",
    "summarize_posterior",
    "uniform_log_prior",
    "write_hierarchical_study_block_records_csv",
    "write_hierarchical_study_summary_csv",
    "write_map_study_fit_records_csv",
    "write_map_study_fit_summary_csv",
    "write_model_comparison_csv",
    "write_posterior_summary_csv",
    "write_study_model_comparison_csv",
    "write_study_model_comparison_subject_csv",
    "write_subject_model_comparison_csv",
    "write_study_fit_records_csv",
    "write_study_fit_summary_csv",
]
