"""
comp_model_core.interfaces.bandit

Environment interfaces (Bandits).

A **BanditEnv** describes the *true* environment dynamics (reward/outcome
generation). It does *not* encode trial-level visibility or action constraints.
Those belong in block runners (see :mod:`comp_model_core.interfaces.block_runner`).

This module defines

- :class:`~comp_model_core.interfaces.bandit_env.EnvStep`: return value of
  :meth:`~comp_model_core.interfaces.bandit_env.BanditEnv.step`
- :class:`~comp_model_core.interfaces.bandit_env.BanditEnv`: base environment
  interface
- :class:`~comp_model_core.interfaces.bandit_env.SocialBanditEnv`: environment
  that can generate demonstrator observations
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Any, Mapping

import numpy as np

from ..spec import EnvironmentSpec
from .block_runner import SocialObservation


@dataclass(frozen=True, slots=True)
class EnvStep:
    """
    Result of a true environment transition.

    This is the return type of :meth:`~BanditEnv.step`. It contains the
    environment's *true* outcome and optional metadata. Visibility/noise
    transformations are applied by a :class:`~comp_model_core.interfaces.block_runner.BlockRunner`,
    not by the environment.

    Parameters
    ----------
    outcome
        True outcome (reward) generated by the environment.
    done
        Whether the environment terminated early (rare for bandits; included for
        generality).
    info
        Optional environment-provided metadata.

    Attributes
    ----------
    outcome : float
        True outcome produced by the environment.
    done : bool
        Whether the episode terminated early.
    info : dict[str, Any] or None
        Optional metadata.

    Notes
    -----
    - For classic stationary bandits, ``done`` is typically always ``False``.
    - If an environment provides additional information (e.g., latent state,
      diagnostic flags), it should be placed in ``info``.
    """

    outcome: float
    done: bool = False
    info: dict[str, Any] | None = None


class BanditEnv(ABC):
    """
    Abstract base class for bandit-like environments.

    A :class:`~BanditEnv` defines the true generative process for outcomes given
    actions. It is responsible for dynamics and state, but not for trial-level
    constraints such as forced-choice action sets or outcome visibility.

    Implementations should be compatible with a
    :class:`~comp_model_core.interfaces.block_runner.BlockRunner`, which applies
    interface constraints and transforms true outcomes into observations.

    Attributes
    ----------
    spec : EnvironmentSpec
        Environment contract (e.g., number of actions and outcome type).

    See Also
    --------
    comp_model_core.interfaces.block_runner.BlockRunner
        Applies trial-level interface constraints and observation models.
    comp_model_core.spec.EnvironmentSpec
        Specification describing the environment's action/outcome interface.
    """

    @classmethod
    @abstractmethod
    def from_config(cls, cfg: Mapping[str, Any]) -> "BanditEnv":
        ...

    @property
    @abstractmethod
    def spec(self) -> EnvironmentSpec:
        """
        Return the environment specification.

        Returns
        -------
        EnvironmentSpec
            Contract describing the environment (e.g., number of actions).
        """
        ...

    @abstractmethod
    def reset(self, *, rng: np.random.Generator) -> Any:
        """
        Reset environment state.

        Parameters
        ----------
        rng
            RNG used to reset any stochastic internal state.

        Returns
        -------
        Any
            Initial state/context identifier, as defined by the environment.
        """
        ...

    @abstractmethod
    def step(self, *, action: int, rng: np.random.Generator) -> EnvStep:
        """
        Apply an action and generate a true outcome.

        Parameters
        ----------
        action
            Action index chosen by the agent.
        rng
            RNG used for stochastic outcome generation and state transitions.

        Returns
        -------
        EnvStep
            Result containing the true outcome, termination flag, and metadata.

        Raises
        ------
        Exception
            Implementations may raise if the action is out of range.
        """
        ...

    @abstractmethod
    def get_state(self) -> Any:
        """
        Return the current environment state/context identifier.

        Returns
        -------
        Any
            Current state, as defined by the environment implementation.
        """
        ...


class SocialBanditEnv(BanditEnv, ABC):
    """
    Environment that can also produce demonstrator observations.

    This interface is used when the environment itself is capable of generating
    demonstrator behavior (e.g., a built-in policy or an auxiliary agent) and
    returning a :class:`~comp_model_core.interfaces.block_runner.SocialObservation`.

    Notes
    -----
    In many designs, demonstrator behavior is implemented at the runner level
    (e.g., via a separate demonstrator model). This interface exists for cases
    where demonstrator dynamics are best treated as part of the environment.

    See Also
    --------
    comp_model_core.interfaces.block_runner.SocialObservation
        Container for demonstrator actions and outcomes.
    """

    @abstractmethod
    def observe_others(self, *, rng: np.random.Generator) -> SocialObservation:
        """
        Produce a demonstrator observation.

        Parameters
        ----------
        rng
            RNG used for stochastic demonstrator dynamics and observation noise.

        Returns
        -------
        SocialObservation
            Demonstrator actions and (true/observed) outcomes, plus metadata.
        """
        ...
