"""comp_model_core.interfaces.bandit

Environment interfaces (bandits).

A :class:`~comp_model_core.interfaces.bandit.BanditEnv` describes *true* environment
dynamics (outcome generation). It does **not** encode trial-level interface rules such as:

- outcome visibility / observation noise,
- action availability constraints.

Those belong to block runners (see :mod:`comp_model_core.interfaces.block_runner`),
which wrap environments and apply trial-varying interface specifications.

Classes
-------
EnvStep
    Return value of :meth:`BanditEnv.step`.
BanditEnv
    Base environment interface.
SocialBanditEnv
    Environment that can produce demonstrator observations.

See Also
--------
comp_model_core.interfaces.block_runner.BlockRunner
comp_model_core.interfaces.block_runner.SocialBlockRunner
comp_model_core.spec.EnvironmentSpec
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Any

import numpy as np

from ..spec import EnvironmentSpec
from .block_runner import SocialObservation


@dataclass(frozen=True, slots=True)
class EnvStep:
    """Result of a true environment transition.

    Attributes
    ----------
    outcome : float
        True outcome generated by the environment.
    done : bool
        Termination flag. Many bandit tasks always return ``False``.
    info : dict[str, Any] or None
        Optional environment-specific metadata.
    """

    outcome: float
    done: bool = False
    info: dict[str, Any] | None = None


class BanditEnv(ABC):
    """Abstract base class for environments.

    Notes
    -----
    Environments are responsible only for generating true outcomes. Any trial-varying
    observation/visibility/noise should be implemented by a block runner, not here.
    """

    @property
    @abstractmethod
    def spec(self) -> EnvironmentSpec:
        """Return the environment contract.

        Returns
        -------
        EnvironmentSpec
            Environment specification (n_actions, outcome semantics, state structure).
        """
        ...

    @abstractmethod
    def reset(self, *, rng: np.random.Generator) -> Any:
        """Reset the environment to the start of a block.

        Parameters
        ----------
        rng : numpy.random.Generator
            Random number generator for stochastic resets.

        Returns
        -------
        Any
            Implementation-defined initial state representation.
        """
        ...

    @abstractmethod
    def step(self, *, action: int, rng: np.random.Generator) -> EnvStep:
        """Advance the environment by one action.

        Parameters
        ----------
        action : int
            Action index chosen by the agent.
        rng : numpy.random.Generator
            Random number generator for stochastic transitions/outcomes.

        Returns
        -------
        EnvStep
            True outcome and optional metadata.
        """
        ...

    @abstractmethod
    def get_state(self) -> Any:
        """Return the current state/context identifier.

        Returns
        -------
        Any
            Implementation-defined state representation (e.g., int state id).
        """
        ...


class SocialBanditEnv(BanditEnv, ABC):
    """Environment that can produce demonstrator/other-agent observations.

    Notes
    -----
    Most of the time, *sociality* is implemented at the runner layer (e.g., by running
    a demonstrator policy in the same environment). This interface exists for tasks
    that can natively produce other-agent signals.
    """

    @abstractmethod
    def observe_others(self, *, rng: np.random.Generator) -> SocialObservation:
        """Produce a demonstrator/other-agent observation.

        Parameters
        ----------
        rng : numpy.random.Generator
            Random number generator for stochastic demonstrator behavior.

        Returns
        -------
        SocialObservation
            Choices and outcomes for the other agent(s).
        """
        ...
