"""
comp_model_core.interfaces.block_runner

Runtime interfaces for executing a single *block* of an experiment.

This module defines the protocol that simulation/replay code interacts with.

Design intent
-------------
The library separates three concerns:

1) **Blueprint (Plan)** – a serializable, stateless description of what to run
   (e.g., :class:`comp_model_core.plans.block.BlockPlan`).
2) **Environment** – the true generative dynamics (e.g., a bandit) producing
   *true* outcomes given actions.
3) **Block runner** – the executable runtime object that:

   - holds environment state,
   - applies trial-level interface constraints (available actions),
   - maps true outcomes to *observations* (hidden / noisy / etc.),
   - (optional) generates social observations via a demonstrator.

We intentionally use the name **BlockRunner** rather than "Task" to avoid
confusion with the blueprint sense of "task".
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Any, Sequence

import numpy as np

from ..spec import EnvironmentSpec, TrialSpec


@dataclass(frozen=True, slots=True)
class StepResult:
    """
    Result of executing one trial in a block.

    This container separates the environment's *true* outcome from the subject's
    *observed* outcome, which may be hidden or corrupted by noise.

    Parameters
    ----------
    outcome
        The *true* outcome generated by the environment for the executed action.
    observed_outcome
        The outcome observation available to the subject/model. This may be
        ``None`` when feedback is hidden, or a noisy transformation of
        ``outcome``.
    done
        Whether the block/episode terminated early.
    info
        Optional additional metadata from the environment/runner.

    Attributes
    ----------
    outcome : float
        True outcome generated by the environment.
    observed_outcome : float or None
        Outcome as observed by the subject/model.
    done : bool
        Whether the block terminated early.
    info : dict[str, Any] or None
        Optional metadata.

    Notes
    -----
    - Many environments always return an ``outcome``; hiding of feedback should
      be represented by setting ``observed_outcome=None`` (not by removing the
      true outcome).
    """

    outcome: float
    observed_outcome: float | None
    done: bool = False
    info: dict[str, Any] | None = None


@dataclass(frozen=True, slots=True)
class SocialObservation:
    """
    Observation about another agent/demonstrator on a given trial.

    This container may include both the demonstrator's true outcomes and the
    subject's observation of those outcomes, enabling models that learn from
    either (or both).

    Parameters
    ----------
    others_choices
        Choices taken by the demonstrator(s) on the trial.
    others_outcomes
        True demonstrator outcomes. Often useful for debugging or evaluating a
        full generative model.
    observed_others_outcomes
        Demonstrator outcomes as visible to the subject/model (may be ``None`` or
        noisy).
    info
        Optional metadata (e.g., which observation model was applied).

    Attributes
    ----------
    others_choices : Sequence[int] or None
        Demonstrator actions.
    others_outcomes : Sequence[float] or None
        True demonstrator outcomes.
    observed_others_outcomes : Sequence[float] or None
        Demonstrator outcomes as observed by the subject/model.
    info : dict[str, Any] or None
        Optional metadata.

    Notes
    -----
    - Social observations are produced by :class:`~SocialBlockRunner` instances.
    - The number of demonstrators is not fixed by this interface; implementations
      may choose to use 0, 1, or many demonstrators.
    """

    others_choices: Sequence[int] | None = None
    others_outcomes: Sequence[float] | None = None
    observed_others_outcomes: Sequence[float] | None = None
    info: dict[str, Any] | None = None


class BlockRunner(ABC):
    """
    Executable runtime interface for a single block.

    A :class:`~BlockRunner` wraps an environment instance and a trial schedule.
    It is stateful: it typically holds environment state and (optionally)
    demonstrator state.

    The generator/replay code drives the time index ``t``; the runner should
    interpret ``t`` consistently with the block blueprint.

    Notes
    -----
    Implementations are responsible for:

    - maintaining any internal environment state,
    - applying trial-level interface constraints (e.g., forced-choice action sets),
    - mapping true outcomes to subject observations (hidden/noisy),
    - optionally supporting social observations via :class:`~SocialBlockRunner`.

    See Also
    --------
    comp_model_core.plans.block.BlockPlan
        Declarative blueprint that specifies the block to run.
    comp_model_core.spec.TrialSpec
        Per-trial interface constraints.
    comp_model_core.spec.EnvironmentSpec
        Environment contract (e.g., number of actions).
    """

    @property
    @abstractmethod
    def spec(self) -> EnvironmentSpec:
        """
        Environment contract for this runner.

        Returns
        -------
        EnvironmentSpec
            Specification describing the action space, outcome type, and any
            relevant environment characteristics.
        """

    @abstractmethod
    def reset(self, *, rng: np.random.Generator) -> Any:
        """
        Reset the block to its initial state.

        Parameters
        ----------
        rng
            RNG used to reset any stochastic environment/runner state.

        Returns
        -------
        Any
            Initial environment state/context identifier, as defined by the
            environment/runner implementation.
        """

    @abstractmethod
    def step(self, *, t: int, action: int, rng: np.random.Generator) -> StepResult:
        """
        Execute one trial.

        Parameters
        ----------
        t
            Trial index within the block.
        action
            Chosen action index.
        rng
            RNG used for stochastic dynamics and observation noise.

        Returns
        -------
        StepResult
            True outcome and observed outcome for this step.

        Raises
        ------
        Exception
            Implementations may raise if ``action`` is invalid for the trial or
            if ``t`` is out of range.
        """

    @abstractmethod
    def get_state(self) -> Any:
        """
        Return the current environment state/context identifier.

        Returns
        -------
        Any
            Current state, as defined by the environment/runner implementation.
        """

    @abstractmethod
    def trial_spec(self, *, t: int) -> TrialSpec:
        """
        Return the trial interface specification for trial ``t``.

        Parameters
        ----------
        t
            Trial index within the block.

        Returns
        -------
        TrialSpec
            Trial-level interface constraints, including outcome visibility/noise
            and optional forced-choice action set.

        Raises
        ------
        Exception
            Implementations may raise if ``t`` is out of range.
        """

    def available_actions(self, *, t: int) -> Sequence[int]:
        """
        Convenience helper returning the allowed action set for trial ``t``.

        If the trial spec does not specify a forced-choice set, this returns the
        full set ``range(spec.n_actions)``.

        Parameters
        ----------
        t
            Trial index within the block.

        Returns
        -------
        Sequence[int]
            Allowed actions for the trial.
        """
        ts = self.trial_spec(t=t)
        if ts.available_actions is None:
            return list(range(int(self.spec.n_actions)))
        return list(ts.available_actions)


class SocialBlockRunner(BlockRunner, ABC):
    """
    A block runner that can provide social/demonstrator observations.

    This extends :class:`~BlockRunner` with an interface to produce observations
    about another agent (or agents) on each trial.

    See Also
    --------
    SocialObservation
        Container for demonstrator actions and (true/observed) outcomes.
    """

    @abstractmethod
    def observe_others(self, *, t: int, rng: np.random.Generator) -> SocialObservation:
        """
        Produce a demonstrator observation for trial ``t``.

        Parameters
        ----------
        t
            Trial index within the block.
        rng
            RNG used for stochastic demonstrator dynamics and observation noise.

        Returns
        -------
        SocialObservation
            Social observation for the trial.

        Notes
        -----
        - Implementations may generate demonstrator behavior lazily (e.g., only
          when observed) or eagerly during :meth:`~BlockRunner.step`.
        """
