"""comp_model_core.interfaces.block_runner

Runtime interfaces for executing a single experimental block.

This module defines the protocol that simulation and replay code interacts with.

The library separates three layers:

1. **Plan / blueprint** (stateless, serializable)
   Describes what to run (e.g., number of trials, trial-specific interface rules).
   See :class:`comp_model_core.plans.block.BlockPlan`.

2. **Environment dynamics** (stateful)
   Generates true outcomes given actions.
   See :class:`comp_model_core.interfaces.bandit.BanditEnv`.

3. **Block runner** (stateful runtime wrapper)
   Applies trial-level interface rules such as action availability and outcome
   observation models (hidden/noisy/veridical), optionally including social
   observation channels.

Notes
-----
The block horizon (``n_trials``) belongs to the plan/dataset layer. Generators and
replayers iterate over trials using the plan's ``n_trials`` and pass the trial
index ``t`` into runner methods.

See Also
--------
comp_model_core.plans.block.BlockPlan
comp_model_core.interfaces.bandit.BanditEnv
comp_model_core.spec.TrialSpec
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Any, Mapping, Sequence

import numpy as np

from ..spec import EnvironmentSpec, ResolvedTrialSpec


@dataclass(frozen=True, slots=True)
class StepResult:
    """Result of stepping a block runner by one trial.

    Attributes
    ----------
    outcome : float
        The *true* outcome generated by the environment.
    observed_outcome : float or None
        The outcome as observed by the subject/model after applying the trial
        interface (e.g., hidden or noisy observation model). ``None`` if feedback
        is hidden on that trial.
    done : bool
        Whether the environment signals termination. Many bandit tasks always
        return ``False``.
    info : Mapping[str, Any] or None
        Optional metadata (e.g., which observation model was applied).
    """

    outcome: float
    observed_outcome: float | None
    done: bool = False
    info: Mapping[str, Any] | None = None


@dataclass(frozen=True, slots=True)
class SocialObservation:
    """Observation about a demonstrator or other agent.

    Attributes
    ----------
    others_choices : Sequence[int] or None
        Demonstrator choices (e.g., a list of one choice per trial).
    others_outcomes : Sequence[float] or None
        Demonstrator *true* outcomes (ground truth).
    observed_others_outcomes : Sequence[float] or None
        Demonstrator outcomes as observed by the subject/model (may be noisy or
        hidden). ``None`` indicates no demonstrator outcomes observed.
    info : Mapping[str, Any] or None
        Optional metadata (e.g., demonstrator outcome observation model details).

    Notes
    -----
    Keeping both true and observed demonstrator outcomes is useful because the
    demonstrator policy may update using true outcomes while the subject/model
    may only see a degraded observation.
    """

    others_choices: Sequence[int] | None = None
    others_outcomes: Sequence[float] | None = None
    observed_others_outcomes: Sequence[float] | None = None
    info: Mapping[str, Any] | None = None


class BlockRunner(ABC):
    """Stateful runtime object for executing a single block.

    A :class:`BlockRunner` wraps an environment and applies trial-level interface
    rules (action availability, outcome observation model, etc.).

    Notes
    -----
    - The runner does **not** own the block horizon. Trial iteration is performed
      by generators/replayers using the plan's ``n_trials``.
    - The runner must expose a resolved trial specification for each trial index.
    - The runner may enforce trial-level action availability.

    See Also
    --------
    comp_model_core.plans.block.BlockPlan
    comp_model_core.interfaces.bandit.BanditEnv
    comp_model_core.spec.ResolvedTrialSpec
    """

    @property
    @abstractmethod
    def spec(self) -> EnvironmentSpec:
        """Environment contract (actions, outcome semantics, state structure)."""
        ...

    @abstractmethod
    def reset(self, *, rng: np.random.Generator) -> Any:
        """Reset the runner and its wrapped environment.

        Parameters
        ----------
        rng : numpy.random.Generator
            Random number generator used for stochastic resets.

        Returns
        -------
        Any
            Implementation-defined state representation returned by the environment.
        """
        ...

    @abstractmethod
    def get_state(self) -> Any:
        """Return the current environment state/context identifier.

        Returns
        -------
        Any
            Implementation-defined state representation (e.g., int state id).
        """
        ...

    @abstractmethod
    def resolved_trial_spec(self, *, t: int) -> ResolvedTrialSpec:
        """Return the fully-resolved interface specification for trial ``t``.

        Parameters
        ----------
        t : int
            Trial index (0-based).

        Returns
        -------
        comp_model_core.spec.ResolvedTrialSpec
            Resolved trial spec with defaults applied.
        """
        ...

    def available_actions(self, *, t: int) -> Sequence[int]:
        """Return the available actions for trial ``t``.

        Parameters
        ----------
        t : int
            Trial index (0-based).

        Returns
        -------
        Sequence[int]
            List of legal action indices for trial ``t``. If the trial spec does
            not constrain actions, returns ``range(spec.n_actions)``.
        """
        rts = self.resolved_trial_spec(t=t)
        if rts.available_actions is None:
            return list(range(int(self.spec.n_actions)))
        return list(rts.available_actions)

    @abstractmethod
    def step(self, *, t: int, action: int, rng: np.random.Generator) -> StepResult:
        """Execute one trial step.

        Parameters
        ----------
        t : int
            Trial index (0-based), provided by the generator/replayer.
        action : int
            Chosen action index.
        rng : numpy.random.Generator
            Random number generator used for stochastic environments and/or
            observation noise.

        Returns
        -------
        StepResult
            True outcome and observed outcome (possibly hidden/noisy), plus metadata.
        """
        ...


class SocialBlockRunner(BlockRunner, ABC):
    """Block runner that supports demonstrator/other-agent observations."""

    @abstractmethod
    def observe_others(self, *, t: int, rng: np.random.Generator) -> SocialObservation:
        """Generate a social observation for trial ``t``.

        Parameters
        ----------
        t : int
            Trial index (0-based).
        rng : numpy.random.Generator
            Random number generator used for stochastic demonstrator behavior or
            noisy observation channels.

        Returns
        -------
        SocialObservation
            Demonstrator choices and outcomes (true and/or observed).
        """
        ...
