name: tests

on:
  push:
  pull_request:

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.14"]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install
        run: |
          python -m pip install -U pip
          python -m pip install pytest
          python -m pip install -e ./comp_model_core
          python -m pip install -e ./comp_model_impl

      - name: Test
        run: python -m pytest